import { Space_Grotesk as spaceGrotesk } from 'next/font/google'
import Header from '../components/Header'
import './globals.css'

const font = spaceGrotesk({ weight: ['400', '700'], subsets: ['latin'] })

export const metadata = [
  {
    title: 'Create Next App',
    description: 'Generated by create next app'
  }
]

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <title>{metadata.title}</title>
      </head>
      <body className={font.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
